test_that("text is returned corrently", {
  expect_equal(get_pc_in_words(1,    "100%"), "all")
  expect_equal(get_pc_in_words(.998, "100%"), "all")
  expect_equal(get_pc_in_words(.98,  "98%"),  "almost all")
  expect_equal(get_pc_in_words(.75,  "75%"),  "three quarters")
  expect_equal(get_pc_in_words(.74,  "74%"),  "around three quarters")
  expect_equal(get_pc_in_words(.66,  "66%"),  "two thirds")
  expect_equal(get_pc_in_words(.65,  "65%"),  "around two thirds")
  expect_equal(get_pc_in_words(.52,  "52%"),  "just over half")
  expect_equal(get_pc_in_words(.5,   "50%"),  "half")
  expect_equal(get_pc_in_words(.47,  "47%"),  "just under half")
  expect_equal(get_pc_in_words(.33,  "33%"),  "a third")
  expect_equal(get_pc_in_words(.31,  "31%"),  "around a third")
  expect_equal(get_pc_in_words(.25,  "25%"),  "a quarter")
  expect_equal(get_pc_in_words(.24,  "24%"),  "around a quarter")
  expect_equal(get_pc_in_words(.2,   "20%"),  "a fifth")
  expect_equal(get_pc_in_words(.19,  "19%"),  "around a fifth")
  expect_equal(get_pc_in_words(.1,   "10%"),  "10%")
})
